import "@/styles/globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

import type { Metadata } from "next";

import LayoutProviders from "@/app/layout-providers";

import Footer from "@/containers/footer";

export const metadata: Metadata = {
  title: "Financial tool",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LayoutProviders>
      <html lang="en">
        <body>
          {children}
          <Footer />
        </body>
      </html>
    </LayoutProviders>
  );
}
