import "./globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

import type { Metadata } from "next";

import { Inter } from "next/font/google";

import LayoutProviders from "@/app/layout-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Financial tool",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LayoutProviders>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </LayoutProviders>
  );
}
