name: e2e_client
on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/e2e-client.yml'
      - '!client/README.md'

jobs:
  e2e_client:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: client
    steps:
    - name: checkout pull
      uses: actions/checkout@v3

    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version-file: 'client/.nvmrc'
        cache: yarn
        cache-dependency-path: 'client/yarn.lock'

    - name: Changes Yarn version
      run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable

    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps

    - name: Run Playwright tests
      run: yarn playwright test
      env:
        NEXT_PUBLIC_URL: http://localhost:3000
        NEXT_PUBLIC_API_URL: http://localhost:1337/cms
        NEXT_PUBLIC_MAPBOX_API_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_TOKEN }}
        # Recommended: pass the GitHub token lets this action correctly
        # determine the unique run id necessary to re-run the checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30